[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "autoconf", "gcc", "gnumake", "openssl", "pkg-config", "php82Packages.mongodb"]

[phases.install]
cmds = [
    "find / -name 'mongodb.so' 2>/dev/null || echo 'NOT FOUND'",
    "composer install --ignore-platform-reqs --optimize-autoloader --no-interaction"
]

[start]
cmd = "php -d extension=mongodb.so -S 0.0.0.0:$PORT -t public/"
